blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooVetGit/Roo-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for Roo Code Paper
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=PaperGames.roo-cline-paper&ssr=false#review-details
      about: Enjoying Roo Code Paper? Leave a review here!
